# Generated by Django 5.1.1 on 2025-02-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronagapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
