# Generated by Django 5.1.1 on 2025-02-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronagapp', '0002_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
