# Generated by Django 5.1.1 on 2025-03-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronagapp', '0006_alter_post_image1_alter_post_image2_alter_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/posts/'),
        ),
    ]
