# Generated by Django 5.1.1 on 2025-03-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronagapp', '0009_alter_post_image1_alter_post_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
    ]
