# Generated by Django 5.1.6 on 2025-03-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronagapp', '0011_post_image3_post_paragraph4_post_paragraph5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='paragraph1',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraph2',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraph3',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraph4',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraph5',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraph6',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
