# Generated by Django 5.1.6 on 2025-03-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronagapp', '0014_alter_post_paragraph1_alter_post_paragraph2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='paragraph1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraph2',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraph3',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraph4',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraph5',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraph6',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
