# Generated by Django 5.1.6 on 2025-06-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronagapp', '0016_imagegroup_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.TextField(blank=True, null=True)),
                ('paragraph', models.TextField(blank=True, max_length=100000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
            ],
        ),
    ]
