# Generated by Django 5.1.6 on 2025-06-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronagapp', '0017_onlinepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
