# Generated by Django 5.1.6 on 2025-06-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronagapp', '0018_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepost',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
