# Generated by Django 5.1.6 on 2026-04-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronagapp', '0020_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='url',
            field=models.URLField(blank=True, help_text='Paste the Google Drive or PDF URL here', max_length=500, null=True),
        ),
    ]
